import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import FireFilesBackground from "./components/FireFilesBackground";
import SoundThemes from "./components/Sound";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "MyProfile",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={clsx(
          inter.variable,
          "bg-background text-foreground font-inter"
        )}
      >
        {children}
        <FireFilesBackground />
        <SoundThemes />
        <div id="my-modal" />
      </body>
    </html>
  );
}
